apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysql-pass
  namespace: deployment-a
spec:
  encryptedData:
    password: AgBgVO6BcBqyicgwr/2WEEy0NOLa5TSyhjhN3GQoYDZhBegWcYVVH7lTBXHmONKV7VhMLRRvxUYTQ60F32yLyKgdc3euSiRWurz5EP8nFABvmbAQI1QcKtRLjD4Uf3lwZXFC0eOmVolpLry2XOCAlUo53lTayK+mr7dK6wfMeS+qzbIUIPZYWlG2885hHDXbMrGdLEVlrHZlZn5B4ljktyc49l+KRaucV2gJyeK7gs9xzGT0LbmiSiC4ZZvbHmP5E8BvHYhdB/HR2ZIu5xcyo73EHKHvI/pkXvFGoiiQ26tep9/xg5eOCPEsFG9fEnluyxiEiEC/WRt7NncTwu4O80PwzzWlWBu0ZpoUdYqk4U7yHMpTpbhOacAnqYEnTeWNrZHyNlfY9Ypg89gZGcFdJGYcqFs70InGKRScNyAW34XhuQDaAljqom7Rn9RoumIdc9KVwiqiVsJPdUcWvxvICRf44xCkUPf0wjp5aQ7Lo8MGNZtAkIBrLjez1Z3RWPh5QqLhrfKX/VAv3/05zh6ZoWLjbE+49e6k8EvUNJcX/MX0j+8NStb+hkKz1COBt+a8pNmsEEcchPODzTfNrGXeMj7yJfkyix7uLL8XmBwIBUN+2bC/S3vLkD+KGlPFc03jast7KiPns1K+uuYKs9w9qmtKL+GPgKfG+LYFpN7kT2xWE7ruJEWZMvGNaYZtTpTR9nn1apT4kymT2OraLw==
  template:
    metadata:
      creationTimestamp: null
      name: mysql-pass
      namespace: deployment-a
    type: Opaque

