apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysql-pass
  namespace: default
spec:
  encryptedData:
    password: AgCCQz/kkSkxK0P/RI6oo9aqIQPSuyDE8wc5+jy8YdPNjblqY3iaTGPN5iZQxFVgSkeQV49OvQXwsOnqZPjaKAojrea6tbjCk4CINwVTdRdZdl9+GhrB5xrgu0ANv0suxGPqF/5hBz2ztlQCQMqPzzxRIuNRngZ4YHBQpnHQ8zC6rL/cvdjFucHC4Crcv5/dLMFrEnIyi6pnetm/fCbQcE9T+ceftdc7pyQU8fYW6VjTZRutq0hXm7JVFwTSE5p9mB3wiYh3wkekrcJnPejSrjOf905cDELOu5vuEaGsJm8248yeaT989xXv7qlRd2wYC0nfyPvsXRq9/vwH1bi4DZwqcq7DGsQ4pJ7qS4Gk9Bx5zVfMh51v8a90AseAPgtjLEJcbiDsyOyHHW2s0jKe4QfSWpc+TOm9ayW9GyljP/JO9tTQ84zmGRaasloS5KXSSKekhMg8al6+UpC+UMOOlakq+niP4I/hKg3SGiBmsQl6y7Oo5xPAdjF5nHfQDt/7pea2qS/KPJEXIjMqq4G+HsOYjKU4Dq4Xt1Uh47RGQjkIiaYPQTjzyQf8Os2oSX3GydWNx9NPJVPzvG7YmQL+Hr+Yp+KIMw+cH9Q+/GsJ/WjFC8nHyOXCXO/vHr8JJDYiMvxoq8zM2htiqDnO29R3zMq+fWPZx/EkXuXANtbjJhMQZ8qO2z1lpKc5QAWIINJK69S+GdVMtFbYDPEPpA==
  template:
    metadata:
      creationTimestamp: null
      name: mysql-pass
      namespace: default
    type: Opaque

